"""empty message

Revision ID: 411a441ab943
Revises: cbccd16321bf
Create Date: 2022-03-28 11:10:21.544217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411a441ab943'
down_revision = 'cbccd16321bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
